/*
*AUTOR: JESUS ANGEL HERNANDEZ MARTINEZ
*FECHA: 25/08/2019
*GRUPO: SABADO
*HORARIO:9 A 11 am
*MATRICULA: 1097195
*/


#include <stdio.h>
#include <stdlib.h>


//DECLARACION DE VARIABLES GLOBALES QUE SE USARAN EN TODOS LAS FUNCIONES, LA VARIABLE X CONTENDRA EL VALOR QUE EL USUARIO CAPTURE
//LAS VARIABLES fun1,fun2,fun3,fun4 CONTENDRAN EL RESULTADO DE LAS EXPRESIONES 
float x;
float fun1;
float fun2;
float fun3;
float fun4;



int main() 
{
//SE DECIDIO CREAR UN CICLO SENCILLO do PARA CAPTURAR DE MANERA ININTERUMPIDA LOS 10 VALORES DE X QUE SERAN EVALUADOS EN LA FUNCION 1

do
{
//SE ENVIA UN MENSAJE A LA PANTALLA PARA QUE EL USUARIO CAPTURE EL VALOR DE X QUE SERA EVALUADO EN LA FUNCION
printf("ASIGNE UN VALOR A LA X: ");
//SE ALMACENA EL VALOR CAPTURADO POR EL USUARIO EN LA VARIABLE X
scanf("%f",&x);
//SE EVALUA X EN LA EXPRESION Y SE LE ASIGNA A LA VARIABLE fun1 
fun1=((x-1)/4)-((x-5)/36);
//SE ENVIA MENSAJE A LA PANTALLA DE LOS RESULTADOS DE LA FUNCION EVALUADA CON CADA VALOR DE X CAPTURADO
printf("\n\t\t\t EL VALOR DE LA FUNCION 1 (x-1)/4 - (x-5)/36 ES IGUAL A = %.2f \n",fun1);


}while (x<10);//EL CICLO TERMINA CUANDO SE CAPTURA EL VALOR 10 DE X PARA FINES PRACTICOS DE CAPTURA DE PANTALLA


//SE ENVIA UN MENSAJE A LA PANTALLA QUE ANUNCIA QUE COMENZARA EL CICLO DE VALUACION DE X EN LA FUNCION 2
printf("\n\t\t\t ----EVALUANDO FUNCION---- 2");

//SE DECIDIO CREAR UN CICLO SENCILLO do PARA CAPTURAR DE MANERA ININTERUMPIDA LOS 10 VALORES DE X QUE SERAN EVALUADOS EN LA FUNCION 2

do
{
//SALTOS DE LINEA
printf("\n\n");
//SE ENVIA UN MENSAJE A LA PANTALLA PARA QUE EL USUARIO CAPTURE EL VALOR DE X QUE SERA EVALUADO EN LA FUNCION
printf("ASIGNE UN VALOR A LA X: ");
//SE ALMACENA EL VALOR CAPTURADO POR EL USUARIO EN LA VARIABLE X
scanf("%f",&x);
//SE EVALUA X EN LA EXPRESION Y SE LE ASIGNA A LA VARIABLE fun2 
fun2=(6*(x+1)/8)-((2*x-3)/16);
//SE ENVIA MENSAJE A LA PANTALLA DE LOS RESULTADOS DE LA FUNCION EVALUADA CON CADA VALOR DE X CAPTURADO
printf("\n\t\t\t EL VALOR DE LA FUNCION 2 6{(x-1)/8 - (2x-3)/16} ES IGUAL A = %.2f\n",fun2);
}while(x<10);//EL CICLO TERMINA CUANDO SE CAPTURA EL VALOR 10 DE X PARA FINES PRACTICOS DE CAPTURA DE PANTALLA

//SE ENVIA UN MENSAJE A LA PANTALLA QUE ANUNCIA QUE COMENZARA EL CICLO DE VALUACION DE X EN LA FUNCION 3
printf("\n\t\t\t ----EVALUANDO ACTIVIDAD 2 FUNCION---- 3");

//SE DECIDIO CREAR UN CICLO SENCILLO do PARA CAPTURAR DE MANERA ININTERUMPIDA LOS 10 VALORES DE X QUE SERAN EVALUADOS EN LA FUNCION 3

do
{
//SALTOS DE LINEA
printf("\n\n");
//SE ENVIA UN MENSAJE A LA PANTALLA PARA QUE EL USUARIO CAPTURE EL VALOR DE X QUE SERA EVALUADO EN LA FUNCION
printf("ASIGNE UN VALOR A LA X: ");
//SE ALMACENA EL VALOR CAPTURADO POR EL USUARIO EN LA VARIABLE X
scanf("%f",&x);
//SE EVALUA X EN LA EXPRESION Y SE LE ASIGNA A LA VARIABLE fun3
fun3=(float)2/3*(x-(1-((x-2)/3)))+1;
//SE ENVIA MENSAJE A LA PANTALLA DE LOS RESULTADOS DE LA FUNCION EVALUADA CON CADA VALOR DE X CAPTURADO
printf("\n\t\t\t EL VALOR DE LA FUNCION 3 2/3[x-(1-((x-2)/3))]+1 ES IGUAL A = %f\n",fun3);
}while(x<10);//EL CICLO TERMINA CUANDO SE CAPTURA EL VALOR 10 DE X PARA FINES PRACTICOS DE CAPTURA DE PANTALLA

//SE ENVIA UN MENSAJE A LA PANTALLA QUE ANUNCIA QUE COMENZARA EL CICLO DE VALUACION DE X EN LA FUNCION 4
printf("\n\t\t\t ----EVALUANDO ACTIVIDAD 2 FUNCION---- 4");

//SE DECIDIO CREAR UN CICLO SENCILLO do PARA CAPTURAR DE MANERA ININTERUMPIDA LOS 10 VALORES DE X QUE SERAN EVALUADOS EN LA FUNCION 4
do

{
//SALTOS DE LINEA     
printf("\n\n");
//SE ENVIA UN MENSAJE A LA PANTALLA PARA QUE EL USUARIO CAPTURE EL VALOR DE X QUE SERA EVALUADO EN LA FUNCION
printf("ASIGNE UN VALOR A LA X: ");
//SE ALMACENA EL VALOR CAPTURADO POR EL USUARIO EN LA VARIABLE X
scanf("%f",&x);
//SE EVALUA X EN LA EXPRESION Y SE LE ASIGNA A LA VARIABLE fun4
fun4=2-((-2*(x+1))-((x-3)/2));
//SE ENVIA MENSAJE A LA PANTALLA DE LOS RESULTADOS DE LA FUNCION EVALUADA CON CADA VALOR DE X CAPTURADO
printf("\n\t\t\t EL VALOR DE LA FUNCION 4 2-[-2(x+1)-(x-3)/2] ES IGUAL A = %f\n",fun4);
}while(x<10);//EL CICLO TERMINA CUANDO SE CAPTURA EL VALOR 10 DE X PARA FINES PRACTICOS DE CAPTURA DE PANTALLA

system("PAUSE");


	return 0;

}
